src/Entity/File.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 */
class File
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Type;

    /**
     * @ORM\Column(type="date")
     */
    private $Created;

    /**
     * @ORM\Column(type="integer")
     */
    private $creator;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hidden;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     */
    private $owner;

    public function getOwner(): ?int
    {
        return $this->owner;
    }

    public function setOwner(int $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?int
    {
        return $this->Type;
    }

    public function setType(int $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->Created;
    }

    public function setCreated(\DateTimeInterface $Created): self
    {
        $this->Created = $Created;

        return $this;
    }

    public function getCreator(): ?int
    {
        return $this->creator;
    }

    public function setCreator(int $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getHidden(): ?bool
    {
        return $this->hidden;
    }

    public function setHidden(bool $hidden): self
    {
        $this->hidden = $hidden;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }
}

templates/registry/new_person.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}

    <style>
        label.required:before {
            content: "* ";
            color: red;
        }
    </style>

    <h2>Dodawanie osoby do kartoteki</h2>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

    <br>

    <b style="color: #ff0000;">*</b> - pole obowiązkowe

    <br>
    <br>

    <a href="/persons/">Wróć do kartotek</a>
{% endblock %}

templates/registry/new_person_file.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}

    <style>
        label.required:before {
            content: "* ";
            color: red;
        }
    </style>

    <h2>Dodawanie wpisu do kartoteki</h2>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

    <br>

    <b style="color: #ff0000;">*</b> - pole obowiązkowe

    <br>
    <br>

    <a href="/persons/view/{{ id }}">Wróć</a>
{% endblock %}

templates/registry/new_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}New user{% endblock %}

{% block body %}

    <style>
        label.required:before {
            content: "* ";
            color: red;
        }
    </style>

    <h2>Tworzenie nowego konta</h2>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

    <br>

    <b style="color: #ff0000;">*</b> - pole obowiązkowe

{% endblock %}

templates/registry/person.html.twig
{% extends 'base.html.twig' %}

{%  block title %}Blog Articles{% endblock %}

{% block body %}
    <h1>Kartoteka osobowa {{ person.name }} {{ person.surname }}</h1>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="/persons/remove/{{ person.id }}">
            <button type="button" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
        </a>
    {% endif %}
    {% if is_granted('ROLE_MOD') %}
        <a href="/persons/edit/{{ person.id }}">
            <button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button>
        </a>
    {% endif %}
    {% if person %}
        <table style="width:100%; margin-top: 5px">
            <tr>
                <th style="width: 15%; background: rgba(106,144,164,0.2); padding: 10px">Dane osobowe</th>
            </tr>
            <tr>
                <td>Imię</td>
                <td>{{ person.name }}</td>
            </tr>
            <tr>
                <td>Nazwisko</td>
                <td>{{ person.surname }}</td>
            </tr>
            <tr>
                <td>Narodziny</td>
                {% if person.birth %}
                    <td>{{ person.birth|date('d.m.Y') }}</td>
                {% else %}
                    <td><i>Brak informacji</i></td>
                {% endif %}
            </tr>
            <tr>
                <td>Płeć</td>
                {% if person.sex is not null %}
                    <td>{{ person.sex|sex }}</td>
                {% else %}
                    <td><i>Brak informacji</i></td>
                {% endif %}
            </tr>
            <tr>
                <a data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    <th style="width: 15%; background: rgba(106,144,164,0.2); padding: 10px">Wygląd</th>
                </a>
            </tr>
            <tr>
                <td>Wzrost</td>
                {% if person.height %}
                    <td>{{ person.height }} cm</td>
                {% else %}
                    <td><i>Brak informacji</i></td>
                {% endif %}
            </tr>
            <tr>
                <td>Kolor skóry</td>
                {% if person.skin %}
                    <td>{{ person.skin|skin }}</td>
                {% else %}
                    <td><i>Brak informacji</i></td>
                {% endif %}
            </tr>
            <tr>
                <td>Waga</td>
                {% if person.weight %}
                    <td>{{ person.weight }} kg</td>
                {% else %}
                    <td><i>Brak informacji</i></td>
                {% endif %}
            </tr>
            <tr>
                <th style="width: 15%; background: rgba(106,144,164,0.2); padding: 10px">Inne</th>
            </tr>
            <tr>
                <td>Data ostatniej zmiany</td>
                <td>{{ person.edited|date('d.m.Y') }}</td>
            </tr>
            <tr>
                <td>Stworzono</td>
                <td>{{ creator_name }} - {{ person.added|date('d.m.Y') }}</td>
            </tr>
        </table>

        <br>

        <h1 style="font-size: 20px">Wpisy w kartotece</h1>
            <a href="/persons/view/{{ person.id }}/addfile"><button type="button" class="btn btn-info btn-sm">Dodaj nowy wpis</button></a>
        {% if files %}
            <table class="table table-hover">
                <thead>
                    <tr class="header">
                        <th scope="col" style="width: 5%">ID</th>
                        <th scope="col" style="width: 15%">Typ</th>
                        <th scope="col" style="width: 30%">Dodano</th>
                        <th scope="col">Treść</th>
                        {% if is_granted('ROLE_ADMIN') %}
                            <th scope="col">Inne</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for file in files %}
                        {% if not file.hidden %}
                        <tr>
                            <td>{{ file.id }}</td>
                            <td>
                            {% if file.type == 0 %}
                                Drogowy
                            {% elseif file.type == 1 %}
                                Karny
                            {% elseif file.type == 2 %}
                                Inny
                            {% endif %}
                            </td>
                            <td>
                                {{ file.created|date('d.m.Y') }}
                                <br>
                                <span style="font-size: 11px"><a href="#">{{ file.creator|username }}</a></span>
                            </td>
                            <td>{{ file.content }}</td>
                            {% if is_granted('ROLE_ADMIN') %}
                            <td>
                                <a href="/files/hide/{{ file.id }}"><span class="badge badge-pill badge-success">Public</span></a>
                            </td>
                            {% endif %}
                        </tr>
                        {% else %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <tr class="table-danger">
                                    <td>{{ file.id }}</td>
                                    <td>
                                        {% if file.type == 0 %}
                                            Drogowy
                                        {% elseif file.type == 1 %}
                                            Karny
                                        {% elseif file.type == 2 %}
                                            Inny
                                        {% endif %}
                                    </td>
                                    <td>
                                        {{ file.created|date('d.m.Y') }}
                                        <br>
                                        <span style="font-size: 11px"><a href="#">{{ file.creator|username }}</a></span>
                                    </td>
                                    <td>{{ file.content }}</td>
                                    {% if is_granted('ROLE_ADMIN') %}
                                    <td>
                                        <a href="/files/hide/{{ file.id }}"><span class="badge badge-pill badge-warning">Ukryte</span></a>
                                    </td>
                                    {% endif %}
                                </tr>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-dismissible alert-warning">
                <h4 class="alert-heading">Brak wpisów</h4>
                <p class="mb-0">Nie znaleziono żadnych wpisów. <a href="{{ person.id }}/addfile">Dodaj nowy wpis.</a></p>
            </div>
        {% endif %}
    {% else %}
        <div class="alert alert-dismissible alert-danger">
            <strong>Wystąpił błąd!</strong> Taka osoba nie istnieje.
        </div>
    {% endif %}

    <br><br><br><br><br>

    <a href="/persons"><button type="button" class="btn btn-outline-warning">Wróć do kartoteki</button></a>
{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}

templates/registry/persons.html.twig
{% extends 'base.html.twig' %}

{%  block title %}database{% endblock %}

{% block body %}
    <h1 style="margin-bottom: 0px;">Los Santos Police Department</h1>
    <h1 style="font-size: 15px;">Database - sekcja osób</h1>

    <a href="/persons/add">
        <button type="button" class="btn btn-danger">Dodaj nową osobę</button>
    </a>

    <div>
        <form method="post" class="form-inline my-2 my-lg-0" style="float: right; margin-bottom: 5px;">
            <input class="form-control mr-sm-2" type="text" name="name" placeholder="Dane osobowe">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Szukaj</button>
        </form>
    </div>

    <br>

    {% if not error %}
        Wszystkich rekordów: {{ pagination.getTotalItemCount }}
        <table id="persons" style="margin-top: 5px;" class="table table-striped">
            <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Dane osobowe
                </th>
                <th>
                    Akcje
                </th>
            </tr>
            </thead>
            <tbody>
            {% for person in pagination %}
                <tr>
                    <td>
                        {{ person.id }}
                    </td>
                    <td>
                        {{ person.name }} {{ person.surname }}
                    </td>
                    <td>
                        <a href="/persons/view/{{ person.id}}">
                            <button type="button" class="btn btn-info btn-sm">
                                <i class="fas fa-eye"></i>
                            </button>
                        </a>
                        {% if app.user.role >= 2 %}
                            <a href="/persons/remove/{{ person.id}}">
                                <button type="button" class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </a>
                        {% endif %}
                        {% if app.user.role >= 1 %}
                        <a href="/persons/edit/{{ person.id}}">
                            <button type="button" class="btn btn-primary btn-sm">
                                <i class="fas fa-edit"></i>
                            </button>
                        </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {{ knp_pagination_render(pagination) }}

    {% else %}
        <div class="alert alert-dismissible alert-danger" style="margin-top: 30px">
            <h4 class="alert-heading">Wystąpił błąd</h4>
            <p class="mb-0">{{ error }}</p>
        </div>
    {% endif %}
{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}

templates/registry/users.html.twig
{% extends 'base.html.twig' %}

{%  block title %}database{% endblock %}

{% block body %}
    <h1 style="margin-bottom: 0px;">LSPD - Command Staff</h1>
    <h1 style="font-size: 15px;">Sekcja pracowników</h1>

    {% if not error %}
        Wszystkich rekordów: {{ pagination.getTotalItemCount }}
        <table id="persons" style="margin-top: 5px; width: 30%" class="table table-striped">
            <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Użytkownik
                </th>
            </tr>
            </thead>
            <tbody>
            {% for user in pagination %}
                <tr>
                    <td>
                        {{ user.id }}
                    </td>
                    <td>
                        <a href="/profile/{{ user.id}}">{{ user.fullname }} <span style="font-size: 11px">({{ user.username }})</span></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {{ knp_pagination_render(pagination) }}

    {% else %}
        <div class="alert alert-dismissible alert-danger" style="margin-top: 30px">
            <h4 class="alert-heading">Wystąpił błąd</h4>
            <p class="mb-0">{{ error }}</p>
        </div>
    {% endif %}

    <a href="/users/add">
        <button type="button" class="btn btn-danger">Stwórz nowe konto</button>
    </a>


{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}